name: start bot

on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '1 7 * * *'
    - cron: '2 13 * * *'
    - cron: '3 19 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  TOKEN : ${{ secrets.NS_TOKEN }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  start:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: write token
      run: |
        touch .env
        echo "NS_TOKEN=$TOKEN" >> .env

    - name: run bot
      run: python trigger.py
